### ISSUE TITLE
Helm chart best practice 

### ISSUE THREAD

**Issue by Max-Levitskiy** [pegasystems/pega-helm-charts#103]
**Is your feature request related to a problem? Please describe.**
Pega chart templates are hard to read and understand. It's easier to parse chart to understand which output should we expect. It cames from break one of Helm's best practice - ["Each resource definition should be in its own template file."](https://v2.helm.sh/docs/chart_best_practices/#structure-of-templates) 

**Describe the solution you'd like**
Split YAML files that generate multiple resources in loops. Places with custom logic in .tpl files and YAML content in .yaml files. Create a .yaml file for each resource and use .tpl files inside to avoid duplication of logic. The redundancy of standard Kubernetes constructions should be totally ok.

**Example**
There is pega-tier-deployment.yaml template file. It can be split to web-tier-deployment.yaml, batch-tier-deployment.yaml and batch-tier-deployment.yaml.

**Comment by maracle6** [comment]
One thing to bear in mind is that deployments may not always follow the pattern expected (web, batch, stream).  For example, marketing/decisioning apps may have many tiers for specific decisioning services.  A robotics app may want a web tier for human users and a separate web tier for robotic users.  And I have seen deployments where users of specific applications are routed to a separate pool of nodes, or a CDH application serves decisions to several different source applications which each have their own pool of nodes for inbound service calls.

**Comment by dcasavant** [comment]
Closing for now because this specific suggestion would break dynamic tiers (please reopen if you have a different suggestion).  

More generally, there are probably more best practices that could/should be followed.  The helper.tpl file for example has grown quite a bit and deserves some refactoring care.  @Max-Levitskiy  please reach out to me when you have time and we can discuss how to best refactor the repo to reflect the growth we have seen to date.
