### ISSUE TITLE
Distributed search does not work OOTB

### ISSUE THREAD

**Issue by Emilio-Pega** [pegasystems/pega-helm-charts#123]
**Describe the bug**
Distributed search (i.e Search on a separate node) requires `indexing/distributed/search_enabled = true` as per https://community.pega.com/knowledgebase/articles/system-administration/troubleshooting-pega-platform-search

However, the value is shipped as blank/false in the standard pega distribution. 

The helm chart SHOULD automatically override the DSS (or maybe the docker image should)

**To Reproduce**
See pega bug BUG-551435 (also I searched the current source and didn't see any place where it was overridden)

**Expected behavior**
Distributed search should work OOTB

**Chart version**
1.2.4

**Server (if applicable, please complete the following information):**
N/A

**Additional context**
N/A

**Comment by Emilio-Pega** [comment]
I'm not 100% sure if this fix should go here or in the docker image...

**Comment by Emilio-Pega** [comment]
I think @dcasavant  wants it in the docker, but will leave that up to the team

**Comment by dcasavant** [comment]
At this point there is no need to put this into the Docker image or Helm charts. This seems like a default value issue. The search group is investigating as part of BUG-551435.  I am going to close this issue because it seems like no change is required in Docker or Helm.  If the investigation leads back here, we can reopen this issue.
