### ISSUE TITLE
found in Chart.yaml, but missing in charts/ directory: cassandra

### ISSUE THREAD

**Issue by Avin28887** [pegasystems/pega-helm-charts#127]
Post configuring pega/values.yaml file; tried executing "helm install" command as per the guidelines provided. Whenever install command is executed, following error pops up. Can you please guide us, what exactly causing the issue -

"Error: found in Chart.yaml, but missing in charts/ directory: cassandra"

Note: we have set below flags in values.yaml for cassandra. As, we do not require cassandra enabled.
# Cassandra automatic deployment settings.
cassandra:
  enabled: false
  persistence:
    enabled: false

Thanks and Regards,
S Ch Avinash
![Cassandra-issue-valuesyaml](https://user-images.githubusercontent.com/63280226/78635875-c8711a00-78c4-11ea-8412-8bba65af672d.JPG)

**Comment by dcasavant** [comment]
Since you downloaded the charts locally instead of referencing the published repository, you will need to add the chart dependency repositories and perform a dependency update.  The [Makefile](https://github.com/pegasystems/pega-helm-charts/blob/master/Makefile#L2) makes this easy but you can also run the commands yourself.

**Comment by dcasavant** [comment]
Closing with above proposed resolution.  Please reopen if the issue persists.
