### ISSUE TITLE
Search cluster is not in a ready state

### ISSUE THREAD

**Issue by brettcurtis** [pegasystems/pega-helm-charts#143]
**Describe the bug**
We are hitting an issue around search. "User marked activity execution to failed with message [ Full text search cluster is not in a ready state. Possible reason(s): Initialization failed / master node not reachable.]" 

A suggestion here is to run the pega resource as a stateful set? Is this a resonable solution? 
https://collaborate.pega.com/question/how-recover-elasticsearch-corruption-without-full-cluster-shutdown

**To Reproduce**
This seems to happen after several restarts.

**Expected behavior**
Search cluster in ready state after subsequent restarts.

**Comment by dcasavant** [comment]
Hi @brettcurtis, you should not run the Pega nodes in a stateful set.  The linked post on community was trying to get a version of Pega working on Kubernetes prior to the official support of it.  

Since this seems to be a bit more complicated than can be resolved over GitHub, can you please open a request with Pega [Global Client Support](https://community.pega.com/support) so we can debug further with you?  You can reference this issue in your support ticket.

**Comment by brettcurtis** [comment]
Thanks @dcasavant - I submitted the request.

**Comment by dcasavant** [comment]
@brettcurtis I am going to close this issue for now since there is an SR.  If this ends up being related to the Helm Charts, we can reopen it.
