### ISSUE TITLE
Is it possible to deploy a cluster with stream nodes without persistent storage (Question)

### ISSUE THREAD

**Issue by PegaBasis** [pegasystems/pega-helm-charts#172]
Hello,

Due to limitations of our Openshift platform that has been given to us, we can't use persistent storage (Persistent volume claims).

My question is. Is it possible to deploy a pega cluster on Openshift, with stream nodes, without using persistent volume claims?

And if so, what are the limitations/threats of doing so?

**Comment by MadhuriArugula** [comment]
@PegaBasis The purpose of making stream and search to deploy as StatefulSets with PVC is to store data like partitions, indexes respectively. If deployed without persistent storage, then they would behave similar to normal Deployments (web, batch) and since pod is ephemeral, whenever a restart of a pod happens, **the data (partitions, indexes) would be lost.**

For the current charts to work with such behavior, you have to remove [volumeClaimTemplate](https://github.com/pegasystems/pega-helm-charts/blob/master/charts/pega/values.yaml#L174-L177) block under stream tier for it to be deployed as a normal Deployment.

**Comment by PegaBasis** [comment]
@MadhuriArugula Thank you for your reply. Is it possible to make the stream/search nodes store their data in the database and therefor not needing the PVC?

**Comment by dcasavant** [comment]
@PegaBasis At this time the Platform expects the stream commit log to be durable and a loss of that data may result in unexpected system behavior.  Since this is not something that is actively tested for/against, I am unable to provide much detail on what would happen.  My best guess is that you would loose any data queued for background processing (assuming platform only and not CDH).

**Comment by PegaBasis** [comment]
Thanks Dave and Madhuri. I have enough information for now.
