### ISSUE TITLE
Resource Requirements for Pods

### ISSUE THREAD

**Issue by dhanoa11** [pegasystems/pega-helm-charts#194]
Hi Folks, 

I am trying to understand the resource requirements for the cluster. My install is on open source K8

As per https://community.pega.com/knowledgebase/articles/client-managed-cloud/cloud/meeting-requirements-and-
prerequisites each POD requires 32GB of RAM which is confusing. 

Considering I have 2 Pods (in web tier) , 2 Pods (in Background) and 1in Search - does this mean I need 5 x 32 GB = 160 GB of RAM? Also looking to find out the CPU requirements for the POD.

**Comment by timlaipega** [comment]
I have been puzzling about that 32G req'mt also, I think it depends on the environment.

**Comment by timlaipega** [comment]
Oh, it seems like you are on minikube, so it's definitely not 32G.

**Comment by dhanoa11** [comment]
Minikube just a local lab environment. The actual environment is going to be on open source k8 , hence the question on how to determine compute

**Comment by zitikay** [comment]
To follow up, is this just a question on "what the resource requirements are" or is there some request here?

**Comment by zitikay** [comment]
Default memory limit for each pod is 8G, and the doc https://community.pega.com/knowledgebase/articles/client-managed-cloud/83/meeting-requirements-and-prerequisites specifies you need at least 16GB per **worker node** but you can have multiple worker nodes in a k8s cluster. If there is an issue or additional questions feel free to reopen this issue, but I think the details have since cleared up
