### ISSUE TITLE
Allow changing location of busybox container

### ISSUE THREAD

**Issue by voor** [pegasystems/pega-helm-charts#22]
If you do not have access to Docker Hub (or it is blocked), you should allow chart users to change the location of the busybox container.

**Comment by cdancy** [comment]
@voor that's not a bad idea. As it stands now you could certainly do this very thing and just amend the template files in the necessary locations but I could certainly see it being made easier if we had the config up-front and center to twiddle. Care to send in a PR?

@dcasavant thoughts?

**Comment by dcasavant** [comment]
@voor Added to the backlog.

**Comment by PegaBasis** [comment]
Hi @dcasavant  What is the latest status of this issue? I would also like to be able to change the busybox image for the pega and pegasearch deployment.

**Comment by rbogendoerfer** [comment]
This issue is causing major issues in client environments, where the K8s cluster does not have direct Internet access. To address this issue the helm charts need to be pulled and modified locally.

As a suggested solution the busybox containers should use the same repository and secret as the Pega images, if those are specified in the pega.yaml file (docker.registry section).
