### ISSUE TITLE
Review Pega BI usage in documentation

### ISSUE THREAD

**Issue by MadhuriArugula** [pegasystems/pega-helm-charts#335]
**Describe the bug**
Review the usage of Pega BI in documentation and edit appropriately.
https://github.com/pegasystems/pega-helm-charts/blob/master/charts/pega/README.md#search-deployment

**Comment by MadhuriArugula** [comment]
@taz-pega-work can you please review this?

**Comment by taz-pega-work** [comment]
@MadhuriArugula I'll work with @Anand-Kotamsetti and @vanga to update this wording and make certain we remove or update the reference to Pega BI appropriately, since it doesn't seem that Pega BI is supported in Pega deployments>>
Use the pegasearch section to configure a deployment of ElasticSearch for searching Rules and Work within Pega. This deployment is used exclusively for Pega search, and is not the same ElasticSearch deployment used by the EFK stack or any other dedicated service such as Pega BI.

Use the pegasearch section to configure the source ElasticSearch service that the Pega Platform deployment uses for searching Rules and Work within Pega. The ElasticSearch service defined here is not related to the ElasticSearch deployment if you defined an EFK stack for logging and monitoring in your Pega Platform deployment.

**Comment by Anand-Kotamsetti** [comment]
Added doc fix in PR https://github.com/pegasystems/pega-helm-charts/pull/337. Hence closing this issue.
