### ISSUE TITLE
Backingservices - srs.srsStorage.provisionInternalESCluster prerequisites

### ISSUE THREAD

**Issue by thomasgpeters** [pegasystems/pega-helm-charts#386]
**Description on this issue**
The documentation in the backingservice helm chart configuration on [Configure backingservices](https://github.com/pegasystems/pega-helm-charts/blob/master/charts/backingservices/README.md) seems a bit vague. It is unclear how the prerequisite step needs to be implemented when choosing provisionInternalESCluster=true

When choosing `true`, there is an indication that running 
Enable this parameter to provision an internally managed and secured Elasticsearch cluster to be used with the SRS (Requires you to run `$ make es-prerequisite NAMESPACE=<NAMESPACE_USED_FOR_DEPLOYMENT>`).

this directive is unclear!  

What steps are needed to create the Elasticsearch cluster with correctly bounded storage?

**Chart version**

- pega/pega           	1.9.3                   
- pega/addons         	1.9.3                    
- pega/backingservices	1.9.3

no customizations as yet!

**Server (if applicable, please complete the following information):**
 - OS: [e.g. Red Hat Enterprise Linux release 8.5 (Ootpa)]
 - Environment: [e.g. OpenShift Container Platform 4.8.27]
 - Database: postgres (PostgreSQL) 10.17

**Additional context**
We would like clarity on the comment to run `make` referencing es-prerequisites.

**Comment by dcasavant** [comment]
@pegasystems/searchservice

**Comment by taz-pega-work** [comment]
To satisfy this point>>It is unclear how the prerequisite step needs to be implemented when choosing provisionInternalESCluster=true

Right now, non-experts have to guess how to get the configurations just right based on the current guidance. The example at the end of the readme is specific but it's not clear just what is going on. I think you should move the specific examples in the Enabling security between SRS and Elasticsearch section after the tables:

After the first table (with tls=enabled and srsStorage.provisionInternalESCluster=true>>> Show a useable backingservices configuration which uses the SRS Docker image version v1.20.7, using ES 7.16.x and show precisely how the dependencies.version line up in the two configuration files (the values.yaml and requirements.yaml). Also include how the certificates can be loaded and which parameters can be used to set authentication in the values yaml file.  

This confusing wording currently exists>To connect to external elasticsearch below configuration needs to be made. - I think this line can be safely removed.

After the second table provide an example (with tls=enabled and srsStorage.provisionInternalESCluster=false). then show in the example the other settings that need to be added to complete connection to the client's externally-managed ES service.

I think two examples might help clients figure out which parameters they have to set, given the path they want to pursue: internal ES cluster or connection to external ES service.

**Comment by kingakowalska1** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/kowak1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/kowak1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/kowak1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US link="#0563C1" vlink="#954F72" style='tab-interval:.5in;
word-wrap:break-word'>


<p class=MsoNormal>Hi,<o:p></o:p></p>

<p class=MsoNormal>First of all, this bug was created on February 7<sup>th</sup>,
2022, so almost a year and a half ago, for the chart release 1.9.3 where the
documentation was much shorter than it is now, and a lot of content was added
to the README in the meantime. I’m not sure how relevant it is anymore. That being
said, I think this documentation would benefit from adding a section describing
the Makefile provisioned with the chart, its purpose and uses. In the SRS
documentation currently being prepared for docs.pega.com, I used something like
this:<o:p></o:p></p>



pega-helm-charts/charts/backingservices/Makefile | Contains scripts for        creating Kubernetes secrets necessary for TLS authentication between SRS        and the Elasticsearch cluster.    For an externally managed        Elasticsearch cluster, use the following make command to pass        your TLS certificates to Kubernetes secrets.      $ make external-es-secrets   NAMESPACE=<NAMESPACE_USED_FOR_DEPLOYMENT>   ELASTICSEARCH_VERSION=<ELASTICSEARCH_VERSION>   PATH_TO_CERTIFICATE=<PATH_TO_CERTS>       For an internally        provisioned open source Elasticsearch cluster, use the following make        command to create TLS certificates for the cluster and pass them to        Kubernetes secrets.      $ make es-prerequisite   NAMESPACE=<NAMESPACE_USED_FOR_DEPLOYMENT>   ELASTICSEARCH_VERSION=<ELASTICSEARCH_VERSION>
-- | --



<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/kowak1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/kowak1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/kowak1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US link="#0563C1" vlink="#954F72" style='tab-interval:.5in;
word-wrap:break-word'>


<p class=MsoNormal>The minimum required change would be to explain what the make
es-prerequisite command does, which is creating TLS certificates based on the
version of Elasticsearch cluster and then creating Kubernetes secrets with the
certificates. For example, I propose to add a clarifying sentence like this to
the table:<o:p></o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>



srsStorage.provisionInternalESCluster | Set to true to        enable this parameter to provide an internally managed and secured        Elasticsearch cluster to be used with the SRS cluster. After you specify        an Elasticsearch version in the SRS Helm chart and save the file, run $        make es-prerequisite NAMESPACE=<NAMESPACE>        ELASTICSEARCH_VERSION=<ELASTICSEARCH_VERSION> to create TLS        certificates for your Elasticsearch cluster and pass them to Kubernetes        secrets.    Where NAMESPACE references        your deployment namespace of the SRS cluster and ELASTICSEARCH_VERSION matches        the Elasticsearch version you want to use in values.yaml and requirements.yaml.
-- | --





</body>

</html>


<p class=MsoNormal>Let me know what you think.<o:p></o:p></p>

<p class=MsoNormal>Thanks,<o:p></o:p></p>

<p class=MsoNormal>Kinga<o:p></o:p></p>


</body>

</html>

**Comment by kingakowalska1** [comment]
Hello,

I fixed the messaging around the makefile commands in https://github.com/pegasystems/pega-helm-charts/pull/677.

Please let me know if there is anything else you require.

Thanks,
Kinga Kowalska

**Comment by kishorv10** [comment]
@kingakowalska1 There is no response from the issue creator. You seem to have worked on it and provided some changes, do you think the issue can be closed?

**Comment by kingakowalska1** [comment]
@kishorv10 Yes, the issue can be closed, the doc was reworked and the makefile commands explained.

**Comment by kingakowalska1** [comment]
Fixed in https://github.com/pegasystems/pega-helm-charts/pull/677.
