### ISSUE TITLE
Consistent labels across all workloads

### ISSUE THREAD

**Issue by brettcurtis** [pegasystems/pega-helm-charts#590]
Howdy! We are trying to configure [Unified Service Tagging](https://docs.datadoghq.com/getting_started/tagging/unified_service_tagging/?tab=kubernetes) across all our Pega workloads.

- pega-web
- pega-batch
- pega-stream
- pega-search

The problem is there is not a consistent way of doing this in the chart unless I'm misunderstanding this PR: https://github.com/pegasystems/pega-helm-charts/pull/470? This doesn't work in my use case because I need a different label for each workload. 

I need to be able to label each workload as well as the Pods. Currently I'm able to label the pods with: `global.tier[0].podLabels` 

Search doesn't have support for labels so the best I have there is: ` pegasearch.custom.env[1].name` but this just adds a variable to the container when again I really want the workload and PODs labeled.

Is this a resonable request or is a W/A available that can help me achieve what I'm after?

**Comment by johnbooth** [comment]
We are having the same issue with the externalized hazelcast, pega-hazelcast.  This service doesn't even support custom environment variables. 

hazelcast.custom.env[1].name

**Comment by kishorv10** [comment]
@brettcurtis podLabels feature is available on the search sub-chart as well. Ref #709 
Do you have any more asks from this issue?

**Comment by brettcurtis** [comment]
Howdy ! 

We need to be able to set the following on:
- pega-web
- pega-batch
- pega-stream
- pega-search

`metadata.labels`
`spec.template.metadata.labels`
`spec.template.metadata.annotations`

Let me know if you need anything else.

**Comment by kishorv10** [comment]
Please see if the below configuration helps,
metadata.labels - `.root.Values.global.pegaTier.labels ` - The same set of labels would be applied to all the deployments. Available for Pega deployments only. Not available for pega-search deployment.
spec.template.metadata.labels - `tier[].podLabels` - Tier specific pod labels. Available for pega-search as well
spec.template.metadata.annotations - `tier[].podAnnotation`  - Tier specific pod annotations. Available for pega-search as well

Can you try and revert?

The gaps are,
1. Unable to specify tier-specific labels to deployment objects.
2. Unable to specify deployment labels for pega-search. 

Since most of the requirements are now supported, are you able to achieve what you're looking for? Do you have specific use cases for the two remaining gaps?

**Comment by brettcurtis** [comment]
Let me take a look and potentially test today but I do know we will need all I mentioned above to get the correct association in Datadog so if there are still gaps we will be unsuccessful.

**Comment by brettcurtis** [comment]
I'll test this next week and report back.

**Comment by brettcurtis** [comment]
Closing this since the only services that need to handle labels better now are services that will soon be externalized.
