### ISSUE TITLE
Azure Keyvalut secrets config  are not working in Pega systems

### ISSUE THREAD

**Issue by vvinothkumar1** [pegasystems/pega-helm-charts#599]
**Is your feature request related to a problem? Please describe.**
Presently we are not able to create Azure keyvalut secrets and make Pega AKS run with AKS secrets,  presently we are using Kubernetes Secrets only.  

**Describe the solution you'd like**
Like to use AKS secrets instead of Kubernetes secrets. 

**Describe alternatives you've considered**
presently using Kubernetes secrets. 

**Additional context**
Please have document here or send us if you already have that facliities to configure  secrets in AKS so Pega can use from AKS server instead of using from Kubernetes secrets.

**Comment by arvasrikanth** [comment]
@vvinothkumar1 Pega already supports external secret feature to store credentials and other sensitive information. Can you check [documentation](https://github.com/pegasystems/pega-helm-charts/blob/master/charts/pega/README.md#optional-support-for-providing-credentialscertificates-using-external-secrets-operator) here.

**Comment by DylanAlloy** [comment]
> @vvinothkumar1 Pega already supports external secret feature to store credentials and other sensitive information. Can you check [documentation](https://github.com/pegasystems/pega-helm-charts/blob/master/charts/pega/README.md#optional-support-for-providing-credentialscertificates-using-external-secrets-operator) here.

What is expected behavior? We have a `secret.yaml` file in `templates/` dir of the chart and have declared its name in `external_secret_name` and yet Pega creates a secret and appends onto it the name we have given for `external_secret_name`...?

<img width="1201" alt="Screenshot 2023-08-03 at 10 01 45 AM" src="https://github.com/pegasystems/pega-helm-charts/assets/12659763/5cbfe64c-6121-4834-8c11-8b1b39bcd469">
<img width="786" alt="Screenshot 2023-08-03 at 10 03 17 AM" src="https://github.com/pegasystems/pega-helm-charts/assets/12659763/8b321f80-9d05-4238-9f0a-73ad3173d5b5">
<img width="491" alt="Screenshot 2023-08-03 at 10 03 27 AM" src="https://github.com/pegasystems/pega-helm-charts/assets/12659763/dfa9229a-0af0-4f27-a065-253d4dc9128d">

This is not created by us nor do we wish to use it yet it is being made and contains no useful information for deployment thus Tomcat FAILURE on context.xml read attempt.

Please advise, this behavior seems odd.

**Comment by kishorv10** [comment]
Hi, @mxchinegod Can you please try it again? We have made a few changes to the secrets created as part of #632. This would remove the duplicate secret creation. 
Please try the deployment on the latest chart version. Revert to us in case of any issues.
