### ISSUE TITLE
Set mode to leverage custom prlog4j.xml file for web pods

### ISSUE THREAD

**Issue by sunnygoel8** [pegasystems/pega-helm-charts#77]
What attribute do I need to set in Values.yaml file to leverage custom prlog4j.xml file for Pega web nodes ?

**Comment by dcasavant** [comment]
@sunnygoel8 it should be part of a tier's specification.  The [pega configuration files](https://github.com/pegasystems/pega-helm-charts/tree/master/charts/pega#pega-configuration-files) section of the readme covers the option.  Have you encountered problems with that?

**Comment by sunnygoel8** [comment]
@dcasavant , Thanks for the prompt response. I was looking for the location to drop "prlog4j2Path" paramater in Values.yaml file. But I got my answer. I will include that in tier's specification pointing to xml file on my workstation and try it.. I'll keep you posted..

**Comment by Emilio-Pega** [comment]
@dcasavant Has that ever been tested?  My understanding of the `.root.Files.Get` in the template is that it can only "see" things inside the chart, so if you send it like an external file on your host system, then I'm pretty sure it doesn't really work.

https://v3.helm.sh/docs/chart_template_guide/accessing_files/

https://github.com/helm/helm/issues/3276

**Comment by Emilio-Pega** [comment]
I ran across this issue like a year ago when we were rolling our own charts for marketing so maybe newer versions of helm fix it, but based on the issue I posted above, I don't think it has been

**Comment by sunnygoel8** [comment]
@Elimio-Pega, Thanks for your inputs. 

@dcasavant, could you please confirm that we can leverage external files on our workstation ?

**Comment by dcasavant** [comment]
@Emilio-Pega That sounds like a bug, but not out of the realm of possibility.

@sunnygoel8 This was tested some time back and worked, but it may have been with the chart itself available.  Your options are:

1. Inject a local prlog4j.xml at `helm install` time with a remote chart. This may be a problem due to [this issue](https://github.com/helm/helm/issues/3276) which @Emilio-Pega found.
2. Clone the chart repo and edit the prlog4j.xml file before running `helm install` with your local chart.
3. Deploy as usual, and change the prlog4j.xml in the created configmap. (Not easily repeatable in a CD pipeline).

If an option like 1 is preferable, there is a workaround posted in the Helm issue thread that may be something to incorporate here.  For now, the worst case scenario is option 2.

**Comment by Emilio-Pega** [comment]
We coded a workaround for prconfig.xml and context.xml into the templates where we can pass the full text of the files in (was meant to work-around the issue).  If someone can confirm that this is an actual problem, we can do a similar workaround in the templates for the log file....

https://github.com/pegasystems/pega-helm-charts/blob/master/charts/pega/templates/_pega-config.tpl#L20

**Comment by dcasavant** [comment]
This has been open with an open question for some time.  I am going to close the issue due to inactivity.  @sunnygoel8 feel free to reopen if the problem/usecase persists.

**Comment by sunnygoel8** [comment]
@dcasavant , we are extending pega docker image to include our custom prlog4j2.xml and prConfig.xml files, instead of customizing the Pega helm chart. Do you recommend the former option ?
