### ISSUE TITLE
Error from server (BadRequest): container "pega-web-tomcat" in pod "pega-web-55d95d6c57-j5b54" is waiting to start: PodInitializing"

### ISSUE THREAD

**Issue by SuryaRajud09** [pegasystems/pega-helm-charts#792]
Hi Team,

I am also facing the same issue
" Defaulted container "pega-web-tomcat" out of: pega-web-tomcat, wait-for-pegainstall (init), wait-for-pegasearch (init)
Error from server (BadRequest): container "pega-web-tomcat" in pod "pega-web-55d95d6c57-j5b54" is waiting to start: PodInitializing"

even my pega-search pod is running but still web, batch and stream pods are not running

![image](https://github.com/user-attachments/assets/8ef7ac2f-be9b-4b20-bdf3-169f87f44eb3)

**Comment by zitikay** [comment]
@SuryaRajud09 "I am also facing the same issue", is this reference to issue #233 ? Have you checked on status of init containers? What `action` have you set in values.yaml? seems this is `install-deploy` action, and I can see in screenshot that the pega-db-install pod is still in progress. We have wait-for-pegainstall init container because we cannot bring up the pega-web-tomcat container until the DB has a fully installed application

**Comment by zitikay** [comment]
@SuryaRajud09 it is expected that these pods with init containers do not start until the install job is successfully completed. If you still have problems running these pods you can re-open this issue, if that is the case, please also include relevant info for debugging such as:
* status of install job (needs to be successful before these pods will run)
* Pod events for not-running pods
* helm values (specifically `global.actions.execute:` value in this case)
